config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users
  resources :links
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :url, :url => true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, uniqueness: true

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @user = current_user
    @links = current_user.links
  end

  def edit
    @link = Link.find_by(id: params[:id])
    if params[:format].class == String
      if params[:format] == "mark as read"
        @link.update(read: true)
      else
        @link.update(read: false)
      end
      redirect_to links_path
    end
  end

  def create
    link = Link.new(link_params)
    link.user_id = current_user.id
    if link.save(user_id: current_user.id)
      flash[:notice] = "Successfully saved link."
    else
      flash[:notice] = "URL is not valid."
    end
    redirect_to links_path
  end

  def update
    link = Link.find_by(id: params[:id])
    link.update(user_id: current_user.id)
    if link.update(link_params)
      flash[:notice] = "Successfully saved link."
      redirect_to links_path
    else
      flash[:notice] = "Save unsuccessful."
      redirect_to edit_link_path
    end
  end

  private

  def link_params
    params.require(:link).permit(:url, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    params[:session][:email].downcase!
    @user = User.find_by(session_params)
    if @user && @user.authenticate(params[:session][:password])
      session[:current_user_id] = @user.id
      redirect_to links_path
    else
      flash[:notice] = 'Invalid email/password combination'
      render 'new'
    end
  end

  private
  def session_params
    params.require(:session).permit(:email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    if check_password(params["user"]["password_confirmation"], user_params["password"])
      params["user"]["email"].downcase!
      user = User.new(user_params)
      create_user(user)
    else
      flash[:notice] = "Passwords do not match"
      redirect_to_new_user
    end
  end

  def destroy
    session[:current_user_id] = []
    redirect_to root_path
  end

  private

  def create_user(user)
    if user.save
      session[:current_user_id] = user.id
      redirect_to links_path
    else
      redirect_to_new_user
    end
  end

  def redirect_to_new_user
    redirect_to new_user_path
  end

  def check_password(check_password, password)
    check_password == password
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= session[:current_user_id] && User.find_by(id: session[:current_user_id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= form_for(@link) do |f| %>

   <%= f.label :url %>
   <%= f.text_field :url %>

   <%= f.label :title %>
   <%= f.text_field :title %>

   <%= f.submit "Save changes" %>
 <% end %>

app/views/links/index.html.erb
Welcome <%= @user.email %>

<%=  link_to("Sign Out", user_path(@user), :method => :delete)%>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= form_for :link, url: links_path do |f| %>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<% @links.each do |link| %>
  <div id="<%= link.title %>">
    <% if link.read %>
      <p1>
        <%= link.url %>
        <%= link.title %>
      </p1>
      <%= link_to("Mark as unread", edit_link_path(link, "mark as unread")) %>
    <% else %>
      <%= link.url %>
      <%= link.title %>
      <%= link_to("Mark as read", edit_link_path(link, "mark as read")) %>
    <% end %>
    <%= link_to("edit", edit_link_path(link)) %>
  </div>
<% end %>

app/views/users/new.html.erb
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/welcome/index.html.erb
Log In or Sign Up
<%=  link_to("Log in", login_path)%>
<%=  link_to("Sign Up", new_user_path)%>